### ISSUE TITLE
Error creating task:Invalid workflow.  Plugin 'threshold' does not accept the snap content types or the types '[snap.gob]' returned from the previous node.

### ISSUE THREAD

**Issue by vietanh85** [intelsdi-x/snap-plugin-processor-threshold#5]
**Snap daemon version** (use `snapteld -v`):
docker intelsdi/snap:0.15.0_alpine 

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Relevant tools** (e.g. plugins used with Snap):
- **Others** (e.g. deploying with Ansible):

**What happened**:
This is my task:

```yaml
---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow:
    collect:
      metrics:
        /intel/psutil/cpu/cpu-total/user: {}
        /intel/psutil/cpu/cpu-total/system: {}
        /intel/psutil/cpu/cpu-total/idle: {}
        /intel/psutil/load/*: {}
        /intel/psutil/cpu/*/utilization_percentage: {}
        /intel/psutil/load/load1: {}
      process:
        - plugin_name: "threshold"
          config:
            /intel/psutil/load/load1: 2
          publish:
            - plugin_name: "rabbitmq"
              config:
                uri: "rabbitmq:5672"
                exchange_name: "snap"
                routing_key: "metrics"
                exchange_type: "fanout"
                durable: true

```

This is the error:

```
snaptel task create -t task.yaml 
Using task manifest to create task
Error creating task:Invalid workflow.  Plugin 'threshold' does not accept the snap content types or the types '[snap.gob]' returned from the previous node.
```

**What you expected to happen**:

**Steps to reproduce it** (as minimally and precisely as possible):

1. 
2. 
3. 

**Anything else do we need to know** (e.g. issue happens only occasionally):
